### ISSUE TITLE
의존성 설치가 안됩니다.

### ISSUE THREAD

**Issue by mununki** [sungho0205/react-native-Geupsik#2]
yarn으로 설치를 하는데 의존성 설치가 안됩니다.

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/expo/vector-icons.git
Directory: /Users/woonki/Documents/sungho/react-native-Geupsik
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

이 모듈 때문인 것 같습니다. 그런데 이 모듈은 설치를 안해도 되는 것 같아요.
```
"@expo/vector-icons": "expo/vector-icons",
```
> This library is a compatibility layer around [@oblador/react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) to work with the Expo asset system. If you're using React Native without Expo, you have no need for this library -- carry on! (or maybe [check out Expo](https://expo.io/)).
https://github.com/expo/vector-icons

**Comment by moonsung-ho** [comment]
This library is a compatibility layer around [@oblador/react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) to work with the Expo asset system. If you're using React Native without Expo, you have no need for this library -- carry on! (or maybe [check out Expo](https://expo.io/)).
https://github.com/expo/vector-icons
expo를 쓰고 있기 때문에 필요합니다

**Comment by mununki** [comment]
yarn 대신 npm을 이용하니 설치가 잘 되었습니다.
